name: CI

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ["adopt@1.8", "adopt@1.11"]
        scala: ["2.12.15", "2.13.8"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v5
      - name: Lint code
        run: sbt check
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test
